// Copyright The Docker Agent Action authors
// SPDX-License-Identifier: Apache-2.0

/**
 * Unit tests for src/score-risk.
 *
 * Each scoring rule is tested in isolation first (single-variable control),
 * then in combination.  Edge cases and both zero-score exit paths (exclude-paths
 * prefix match and generated-file marker) are verified independently.
 *
 * Baseline score is 1 for any file that survives rules 1, 2, and 6 — ensuring
 * plain application files are never silently auto-excluded alongside
 * intentionally-low-risk files (tests, docs, generated code, JSON configs).
 */
import { describe, expect, it } from 'vitest';
import { parseExcludePrefixes, scoreFiles } from '../score-risk.js';

// ── Fixture helpers ───────────────────────────────────────────────────────────

/**
 * Build a minimal but structurally valid diff section for `filePath`.
 * `addedLines` is a list of raw lines to append; they should already include
 * the leading `+` where needed (e.g. `'+new code'`).
 */
function makeDiff(filePath: string, addedLines: string[] = ['+new line']): string {
  return [
    `diff --git a/${filePath} b/${filePath}`,
    'index abc..def 100644',
    `--- a/${filePath}`,
    `+++ b/${filePath}`,
    '@@ -1,1 +1,2 @@',
    ' existing',
    ...addedLines,
    '',
  ].join('\n');
}

/** Build a diff with exactly `hunkCount` `@@` headers. */
function makeHunksDiff(filePath: string, hunkCount: number): string {
  const lines = [`diff --git a/${filePath} b/${filePath}`, 'index abc..def 100644'];
  for (let i = 0; i < hunkCount; i++) {
    lines.push(`@@ -${i * 10 + 1},1 +${i * 10 + 1},2 @@`);
    lines.push(`+hunk${i}`);
  }
  lines.push('');
  return lines.join('\n');
}

/** Build a diff with `n` added (non-hunk) lines for `filePath`. */
function makeLargeDiff(filePath: string, addedCount: number): string {
  const added = Array.from({ length: addedCount }, (_, i) => `+line${i}`);
  return makeDiff(filePath, added);
}

// ── parseExcludePrefixes ──────────────────────────────────────────────────────

describe('parseExcludePrefixes', () => {
  it('splits, trims, and drops blank lines', () => {
    expect(parseExcludePrefixes('  backend/gen/\n  frontend/src/gen/  \n\n')).toEqual([
      'backend/gen/',
      'frontend/src/gen/',
    ]);
  });

  it('strips CR characters (Windows line-endings)', () => {
    expect(parseExcludePrefixes('backend/gen/\r\nfrontend/src/gen/\r\n')).toEqual([
      'backend/gen/',
      'frontend/src/gen/',
    ]);
  });

  it('returns empty array for empty string', () => {
    expect(parseExcludePrefixes('')).toEqual([]);
  });
});

// ── Rule 1: exclude-paths prefix → score 0 ───────────────────────────────────

describe('scoreFiles — rule 1: exclude-paths prefix → score 0', () => {
  it('file matching the prefix scores 0', () => {
    const diff = makeDiff('backend/gen/foo.pb.go');
    const scores = scoreFiles(diff, ['backend/gen/']);
    expect(scores['backend/gen/foo.pb.go']).toBe(0);
  });

  it('security-path file in excluded prefix still scores 0 (prefix wins)', () => {
    // Without an exclude prefix, "session_service.pb.go" would score 3
    // (baseline 1 + security-path +2), but the exclude-paths rule fires
    // first and short-circuits to 0.
    const diff = makeLargeDiff('backend/gen/session_service.pb.go', 200);
    const scores = scoreFiles(diff, ['backend/gen/']);
    expect(scores['backend/gen/session_service.pb.go']).toBe(0);
  });

  it('non-matching file is scored normally', () => {
    const diff = makeDiff('backend/gen/foo.pb.go') + makeDiff('src/auth/handler.go');
    const scores = scoreFiles(diff, ['backend/gen/']);
    expect(scores['backend/gen/foo.pb.go']).toBe(0);
    expect(scores['src/auth/handler.go']).toBe(3); // baseline 1 + security path +2
  });

  it('multiple prefixes — file matching any is scored 0', () => {
    const diff =
      makeDiff('backend/gen/foo.pb.go') +
      makeDiff('frontend/src/gen/api.ts') +
      makeDiff('src/real.go');
    const scores = scoreFiles(diff, ['backend/gen/', 'frontend/src/gen/']);
    expect(scores['backend/gen/foo.pb.go']).toBe(0);
    expect(scores['frontend/src/gen/api.ts']).toBe(0);
    expect(scores['src/real.go']).toBe(1); // baseline 1: plain file, no signals
  });
});

// ── Rule 2: generated-file marker → score 0 ──────────────────────────────────

describe('scoreFiles — rule 2: generated-file marker → score 0', () => {
  it('"Code generated" in first added line → score 0', () => {
    const diff = makeDiff('src/gen.pb.go', [
      '+// Code generated by protoc-gen-go.  DO NOT EDIT.',
      '+package gen',
    ]);
    const scores = scoreFiles(diff, []);
    expect(scores['src/gen.pb.go']).toBe(0);
  });

  it('"DO NOT EDIT" anywhere in first 5 added lines → score 0', () => {
    const diff = makeDiff('src/gen.pb.go', [
      '+// generated file',
      '+// DO NOT EDIT manually',
      '+package gen',
    ]);
    const scores = scoreFiles(diff, []);
    expect(scores['src/gen.pb.go']).toBe(0);
  });

  it('marker on line 5 (boundary, inclusive of count < 5) → score 0', () => {
    // count reaches 5 on line 5; the loop checks GENERATED_MARKER_RE before
    // the count >= 5 exit, so line 5 (addedCount == 5 after increment) is tested.
    const diff = makeDiff('src/gen.pb.go', [
      '+line1',
      '+line2',
      '+line3',
      '+line4',
      '+// Code generated',
    ]);
    const scores = scoreFiles(diff, []);
    expect(scores['src/gen.pb.go']).toBe(0);
  });

  it('marker beyond line 5 is ignored — file scored normally', () => {
    const diff = makeDiff('src/auth/handler.go', [
      '+line1',
      '+line2',
      '+line3',
      '+line4',
      '+line5',
      '+// Code generated (too late to trigger marker check)',
    ]);
    const scores = scoreFiles(diff, []);
    // Baseline 1 + security path +2 = 3; marker too late to fire.
    expect(scores['src/auth/handler.go']).toBe(3);
  });

  it('marker on context line (not a "+" line) does NOT trigger → scored normally', () => {
    // A context line (space-prefixed) represents a pre-existing generated marker.
    const diff = makeDiff('src/auth/gen.go', [
      ' // Code generated — context, not added',
      '+real change',
    ]);
    const scores = scoreFiles(diff, []);
    // Baseline 1 + security path matches "auth" → +2 = 3; no marker on added line.
    expect(scores['src/auth/gen.go']).toBe(3);
  });
});

// ── Rule 3: security-sensitive path → +2 ─────────────────────────────────────

describe('scoreFiles — rule 3: security-sensitive path → +2', () => {
  const KEYWORDS = [
    'auth',
    'security',
    'crypto',
    'session',
    'secret',
    'token',
    'password',
    'credential',
  ] as const;

  for (const kw of KEYWORDS) {
    it(`keyword "${kw}" in path → score 3 (baseline 1 + security +2)`, () => {
      const diff = makeDiff(`src/${kw}/handler.go`);
      const scores = scoreFiles(diff, []);
      expect(scores[`src/${kw}/handler.go`]).toBe(3);
    });
  }

  it('keyword is case-insensitive (AUTH → 3)', () => {
    const diff = makeDiff('src/AUTH/handler.go');
    const scores = scoreFiles(diff, []);
    expect(scores['src/AUTH/handler.go']).toBe(3);
  });

  it('no keyword in path → baseline score 1', () => {
    const diff = makeDiff('src/utils/helper.go');
    const scores = scoreFiles(diff, []);
    expect(scores['src/utils/helper.go']).toBe(1);
  });
});

// ── Rule 4: large change (>100 added lines) → +2 ─────────────────────────────

describe('scoreFiles — rule 4: large change (>100 added lines) → +2', () => {
  it('101 added lines → score 3 (baseline 1 + large +2)', () => {
    const diff = makeLargeDiff('src/big.go', 101);
    const scores = scoreFiles(diff, []);
    expect(scores['src/big.go']).toBe(3);
  });

  it('100 added lines (boundary) → score 1 (baseline only; rule not triggered)', () => {
    const diff = makeLargeDiff('src/big.go', 100);
    const scores = scoreFiles(diff, []);
    expect(scores['src/big.go']).toBe(1);
  });

  it('1 added line → score 1 (baseline only)', () => {
    const diff = makeDiff('src/small.go', ['+one line']);
    const scores = scoreFiles(diff, []);
    expect(scores['src/small.go']).toBe(1);
  });
});

// ── Rule 5: many hunks (>3) → +1 ─────────────────────────────────────────────

describe('scoreFiles — rule 5: many hunks (>3 hunk headers) → +1', () => {
  it('4 hunks → score 2 (baseline 1 + hunks +1)', () => {
    const diff = makeHunksDiff('src/hunky.go', 4);
    const scores = scoreFiles(diff, []);
    expect(scores['src/hunky.go']).toBe(2);
  });

  it('3 hunks (boundary) → score 1 (baseline only; rule not triggered)', () => {
    const diff = makeHunksDiff('src/hunky.go', 3);
    const scores = scoreFiles(diff, []);
    expect(scores['src/hunky.go']).toBe(1);
  });

  it('1 hunk → score 1 (baseline only)', () => {
    const diff = makeDiff('src/simple.go', ['+change']);
    const scores = scoreFiles(diff, []);
    expect(scores['src/simple.go']).toBe(1);
  });
});

// ── Rule 6: test/doc/config file → reset score to 0 ──────────────────────────

describe('scoreFiles — rule 6: Rust/Ruby test/bench/spec suffixes → reset score to 0', () => {
  it('Rust file in tests/ directory scores 0 (directory component match)', () => {
    const diff = makeDiff('crates/vm/tests/integration/virtiofs.rs');
    const scores = scoreFiles(diff, []);
    expect(scores['crates/vm/tests/integration/virtiofs.rs']).toBe(0);
  });

  it('Rust bench file in benches/ directory scores 0 (directory component match)', () => {
    const diff = makeDiff('crates/hypervisor/benches/kvm_bench.rs');
    const scores = scoreFiles(diff, []);
    expect(scores['crates/hypervisor/benches/kvm_bench.rs']).toBe(0);
  });

  it('Ruby spec file by suffix scores 0', () => {
    const diff = makeDiff('spec/models/user_spec.rb');
    const scores = scoreFiles(diff, []);
    expect(scores['spec/models/user_spec.rb']).toBe(0);
  });

  it('file in tests/ directory with security keyword in path resets to 0 (rule 6 wins)', () => {
    // "auth" in path would normally add +2 (rule 3), but tests/ directory resets to 0
    const diff = makeDiff('src/auth/tests/handler_test.go');
    const scores = scoreFiles(diff, []);
    // Rule 7 (error handling) can still apply; rule 3 (+2) + baseline (1) are reset by rule 6.
    // No error-handling keywords in the default diff content, so score stays 0.
    expect(scores['src/auth/tests/handler_test.go']).toBe(0);
  });

  it('Rust _test.rs suffix scores 0', () => {
    const diff = makeDiff('src/vm/memory_test.rs');
    const scores = scoreFiles(diff, []);
    expect(scores['src/vm/memory_test.rs']).toBe(0);
  });

  it('Rust _bench.rs suffix scores 0', () => {
    const diff = makeDiff('src/crypto/hash_bench.rs');
    const scores = scoreFiles(diff, []);
    expect(scores['src/crypto/hash_bench.rs']).toBe(0);
  });

  it('Rust _spec.rs suffix scores 0', () => {
    const diff = makeDiff('src/auth/token_spec.rs');
    const scores = scoreFiles(diff, []);
    expect(scores['src/auth/token_spec.rs']).toBe(0);
  });

  it('__tests__/ directory component scores 0', () => {
    const diff = makeDiff('src/auth/__tests__/handler.ts');
    const scores = scoreFiles(diff, []);
    expect(scores['src/auth/__tests__/handler.ts']).toBe(0);
  });

  it('specs/ directory component scores 0', () => {
    const diff = makeDiff('lib/specs/my_spec.rb');
    const scores = scoreFiles(diff, []);
    expect(scores['lib/specs/my_spec.rb']).toBe(0);
  });
});

describe('scoreFiles — rule 6: test/doc/config file → reset score to 0', () => {
  const TEST_PATHS = [
    'src/auth_test.go',
    'src/auth.test.ts',
    'src/auth.test.tsx',
    'src/auth.test.js',
    'src/auth.test.jsx',
    'src/auth.spec.ts',
    'src/auth.spec.tsx',
    'test_auth.py',
    'docs/README.md',
    '.github/workflows/ci.yml',
    '.github/workflows/ci.yaml',
    'config/app.json',
    'config/pyproject.toml',
  ] as const;

  for (const p of TEST_PATHS) {
    it(`"${p}" resets score to 0 even with security-path match`, () => {
      // Use a large diff to trigger rules 3, 4, 5 — all should be overridden by rule 6.
      const lines = Array.from({ length: 110 }, (_, i) => `+line${i}`);
      const hunkHeaders = Array.from(
        { length: 4 },
        (_, i) => `@@ -${i * 5 + 1},1 +${i * 5 + 1},2 @@`,
      );
      const diff = [
        `diff --git a/${p} b/${p}`,
        'index abc..def 100644',
        `--- a/${p}`,
        `+++ b/${p}`,
        ...hunkHeaders.flatMap((h) => [h, '+hunk']),
        ...lines,
        '',
      ].join('\n');
      const scores = scoreFiles(diff, []);
      // Rule 6 resets to 0 (overrides baseline + rules 3-5); rule 7
      // (error-handling keywords) can still add +1 after the reset, but
      // no error-handling keywords appear in this diff, so the score stays 0.
      expect(scores[p]).toBe(0);
    });
  }

  it('test file WITH error-handling patterns scores 1 (rule 7 still applies after reset)', () => {
    // Rule 6 resets the running total to 0, then rule 7 adds 1.
    const diff = makeDiff('src/auth_test.go', ['+if err != nil { panic(err) }']);
    const scores = scoreFiles(diff, []);
    expect(scores['src/auth_test.go']).toBe(1);
  });
});

// ── Rule 7: error-handling patterns → +1 ─────────────────────────────────────

describe('scoreFiles — rule 7: error-handling patterns → +1', () => {
  const KEYWORDS = ['catch', 'rescue', 'except', 'recover', 'error', 'panic'] as const;

  for (const kw of KEYWORDS) {
    it(`keyword "${kw}" in an added line → baseline 1 + error +1 = 2`, () => {
      const diff = makeDiff('src/service.go', [`+handle ${kw} here`]);
      const scores = scoreFiles(diff, []);
      expect(scores['src/service.go']).toBe(2);
    });
  }

  it('keyword in a context line (not added) → no +1 (baseline 1 only)', () => {
    // Context line (space-prefixed) doesn't count.
    const diff = makeDiff('src/service.go', [' existing catch block', '+new line only']);
    const scores = scoreFiles(diff, []);
    expect(scores['src/service.go']).toBe(1);
  });

  it('multiple error-handling lines still only add +1 total (baseline 1 + error +1 = 2)', () => {
    const diff = makeDiff('src/service.go', [
      '+catch(err) {',
      '+  recover();',
      '+  panic(err)',
      '}',
    ]);
    const scores = scoreFiles(diff, []);
    expect(scores['src/service.go']).toBe(2);
  });
});

// ── Combined scoring ──────────────────────────────────────────────────────────

describe('scoreFiles — combined rules', () => {
  it('security path + large change = 5 (baseline 1 + security +2 + large +2)', () => {
    const diff = makeLargeDiff('src/auth/handler.go', 150);
    const scores = scoreFiles(diff, []);
    expect(scores['src/auth/handler.go']).toBe(5);
  });

  it('security path + large change + many hunks = 6 (baseline 1 + security +2 + large +2 + hunks +1)', () => {
    const lines = Array.from({ length: 110 }, (_, i) => `+line${i}`);
    const hunkHeaders = Array.from(
      { length: 4 },
      (_, i) => `@@ -${i * 30 + 1},1 +${i * 30 + 1},2 @@`,
    );
    const diff = [
      'diff --git a/src/session/service.go b/src/session/service.go',
      'index abc..def 100644',
      '--- a/src/session/service.go',
      '+++ b/src/session/service.go',
      ...hunkHeaders.flatMap((h) => [h, '+hunk']),
      ...lines,
      '',
    ].join('\n');
    const scores = scoreFiles(diff, []);
    expect(scores['src/session/service.go']).toBe(6);
  });

  it('security path + large change + many hunks + error handling = 7 (max realistic)', () => {
    const lines = Array.from({ length: 110 }, (_, i) => `+line${i}`);
    const hunkHeaders = Array.from(
      { length: 4 },
      (_, i) => `@@ -${i * 30 + 1},1 +${i * 30 + 1},2 @@`,
    );
    const diff = [
      'diff --git a/src/session/service.go b/src/session/service.go',
      'index abc..def 100644',
      '--- a/src/session/service.go',
      '+++ b/src/session/service.go',
      ...hunkHeaders.flatMap((h) => [h, '+hunk']),
      '+catch(err) {',
      ...lines,
      '',
    ].join('\n');
    const scores = scoreFiles(diff, []);
    expect(scores['src/session/service.go']).toBe(7);
  });

  it('multiple files in one diff are scored independently', () => {
    const diff =
      makeDiff('src/auth/handler.go') + // baseline 1 + security +2 = 3
      makeLargeDiff('src/utils/big.go', 200) + // baseline 1 + large +2 = 3
      makeDiff('backend/gen/foo.pb.go'); // excluded → 0

    const scores = scoreFiles(diff, ['backend/gen/']);
    expect(scores['src/auth/handler.go']).toBe(3);
    expect(scores['src/utils/big.go']).toBe(3);
    expect(scores['backend/gen/foo.pb.go']).toBe(0);
  });
});

// ── extractFilePath regression: greedy-regex vs indexOf(' b/') ─────────────────

describe('scoreFiles — extractFilePath: indexOf regression for paths containing b/', () => {
  it('path with security keyword before a b/ directory component scores 3, not 1', () => {
    // Old greedy regex: replace(/.*b\//, '') on
    //   "diff --git a/src/auth/b/helper.ts b/src/auth/b/helper.ts"
    // matches everything up to the last 'b/' giving 'helper.ts'.
    // 'helper.ts' has no security keyword → baseline score 1 only.
    //
    // New indexOf(' b/'): strips "diff --git a/" prefix and splits at the
    // first ' b/' separator giving 'src/auth/b/helper.ts'.
    // 'src/auth/b/helper.ts' matches SECURITY_PATH_RE ('auth') → baseline 1 + +2 = 3.
    const diff = makeDiff('src/auth/b/helper.ts', ['+changed']);
    const scores = scoreFiles(diff, []);
    expect(scores['src/auth/b/helper.ts']).toBe(3);
  });
});

// ── Baseline score for plain application files ────────────────────────────────

describe('scoreFiles — baseline score 1 for plain application files', () => {
  it('plain app file (src/app.ts) with a small change gets score 1, not 0', () => {
    // This is the key regression test: ordinary application code must never
    // be auto-excluded alongside intentionally-low-risk files.
    const diff = makeDiff('src/app.ts', ['+const x = 1;']);
    const scores = scoreFiles(diff, []);
    expect(scores['src/app.ts']).toBe(1);
  });

  it('plain server file (src/server.ts) scores 1', () => {
    const diff = makeDiff('src/server.ts', ['+app.listen(3000);']);
    const scores = scoreFiles(diff, []);
    expect(scores['src/server.ts']).toBe(1);
  });

  it('plain types file (src/types.ts) scores 1', () => {
    const diff = makeDiff('src/types.ts', ['+export type Foo = string;']);
    const scores = scoreFiles(diff, []);
    expect(scores['src/types.ts']).toBe(1);
  });

  it('React component (src/TeamDetail.tsx) scores 1', () => {
    const diff = makeDiff('src/TeamDetail.tsx', ['+export default function TeamDetail() {}']);
    const scores = scoreFiles(diff, []);
    expect(scores['src/TeamDetail.tsx']).toBe(1);
  });

  it('service file (src/entityEnrichment.ts) scores 1', () => {
    const diff = makeDiff('src/entityEnrichment.ts', ['+export function enrich() {}']);
    const scores = scoreFiles(diff, []);
    expect(scores['src/entityEnrichment.ts']).toBe(1);
  });

  it('plain Go file (internal/handler/http.go) scores 1', () => {
    const diff = makeDiff('internal/handler/http.go', ['+func handleRequest() {}']);
    const scores = scoreFiles(diff, []);
    expect(scores['internal/handler/http.go']).toBe(1);
  });
});

// ── Edge cases ────────────────────────────────────────────────────────────────

describe('scoreFiles — edge cases', () => {
  it('empty diff → empty scores object', () => {
    expect(scoreFiles('', [])).toEqual({});
  });

  it('empty exclude prefixes → all files scored normally (plain files get baseline 1)', () => {
    const diff = makeDiff('backend/gen/foo.pb.go');
    const scores = scoreFiles(diff, []);
    // No security keyword, no large change, no hunks, not a test/doc/config file.
    // makeDiff() does not emit a "Code generated" or "DO NOT EDIT" added line,
    // so rule 2 (generated-file marker) does not fire — the file gets baseline 1.
    expect(scores['backend/gen/foo.pb.go']).toBe(1);
  });

  it('single plain file with no matching rules → baseline score 1', () => {
    const diff = makeDiff('src/utils/helper.go', ['+minor tweak']);
    const scores = scoreFiles(diff, []);
    expect(scores['src/utils/helper.go']).toBe(1);
  });
});
